# Generated by Django 3.1.6 on 2021-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_library', '0002_auto_20210207_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photo/%Y/%m/%d', verbose_name='Изображение книги'),
        ),
    ]
