# Generated by Django 3.1.6 on 2021-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_library', '0003_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photo', verbose_name='Изображение книги'),
        ),
    ]
